name: owlet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.4+18

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  animations: ^2.0.2
  app_tracking_transparency: ^2.0.1
  auto_size_text_field: ^1.0.1
  avatar_glow: ^2.0.2
  badges: ^2.0.1
  bubble: ^1.2.1
  cached_network_image: null
  camera: ^0.9.4+8
  cloudinary_public: ^0.11.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  dropdown_search: ^2.0.1
  emoji_picker_flutter: ^1.1.1
  file_picker: ^4.3.3
  file_selector: ^0.8.2+1
  firebase_analytics: ^9.1.0
  firebase_core: ^1.8.0
  firebase_messaging: ^11.1.0
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_chat_ui: ^1.5.3
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^9.0.2
  flutter_native_splash: ^2.0.5
  flutter_svg: ^1.0.3
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.1.0
  geolocator: ^8.2.0
  grouped_list: ^4.1.0
  hashtagable: ^2.0.2+1
  http: null
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+5
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  insta_like_button: ^0.1.1
  jiffy: ^5.0.0
  lazy_load_scrollview: ^1.3.0
  like_button: ^2.0.3
  material_design_icons_flutter: ^5.0.6595
  mime: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  overlay_support: ^1.2.1
  path: ^1.8.0
  photo_manager: ^2.0.2
  platform_device_id: ^1.0.1
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  readmore: null
  rflutter_alert: ^2.0.4
  scroll_to_index: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  social_media_widgets: ^1.0.0+2
  socket_io_client: ^1.0.2
  sqflite: ^2.0.2
  story: ^0.6.0
  story_view: ^0.13.2
  top_snackbar_flutter: ^1.0.1
  transparent_image: ^2.0.0
  upgrader: ^3.5.1
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0
  video_compress: ^3.1.0
  video_player: ^2.2.10
  wakelock: ^0.6.1+1
  flutter_share: ^2.0.0
  share: ^2.0.4
  flutter_email_sender: ^5.1.0
  flutter_paystack: ^1.0.5+1
  google_fonts: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'
  image_path: 'assets/icons/app-icon.jpg'
   

# The following section is specific to Flutter.
flutter_native_splash:
  background_image: assets/images/splash_screen.png
  image: assets/images/transbase.png

  #background_image: "assets/background.png"
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
